version: '3.7'
services:
  db:
    platform: linux/x86_64 #M1チップ対応のためプラットフォームを指定
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql:delegated
    ports:
      - '4306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    env_file: .env
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - .:/xxx8110io:cached
      - bundle:/usr/local/bundle:delegated
      - node_modules:/xxx8110io/node_modules
      - tmp-data:/xxx8110io/tmp/sockets

volumes:
  mysql:
  bundle:
  node_modules:
  tmp-data: